name: 'Configure ssh'
description: ''
inputs:
  host:
    description: 'Host'
    required: true
  username:
    description: 'User'
    default: 'ubuntu'
  key:
    required: true
    default: 'Key'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: configure.sh
      shell: bash
      env:
        SSH_USER: ${{ inputs.USERNAME }}
        SSH_KEY: ${{ inputs.KEY }}
        SSH_HOST: ${{ inputs.HOST }}